# # Logger level
level: info

# # FLV Options
flv_archive: false
flv_dir: "./tmp"
httpflv_addr: ":7001"

# # RTMP Options
rtmp_noauth: true
rtmp_addr: ":1935"
read_timeout: 5
write_timeout: 5

# # RTMP on Websocket Options
ws_cert: "/root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/*******.crt"
ws_key: "/root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/*******.key"
ws_addr: ":7002"
ws_dst: "127.0.0.1:1935"
server:
- appname: live
  live: true
  hls: false
  api: false
  flv: true
  ws: true